"use client";

import { useEffect, useRef, useState } from "react";

const seedEvents: Array<readonly [string, string, string, string]> = [["02:14:08", "WATCHMAN", "CVE-2025-4723 found in lodash@4.17.20", "critical"], ["02:14:15", "CODEX", "Drafted package-lock.json patch · 3 tests passed", "cyan"], ["02:17:42", "DETECTIVE", "Root cause isolated to auth middleware commit a17e9", "violet"], ["02:18:03", "JANITOR", "Found 12 unused imports across 4 modules", "muted"]];
type Replay = { agent: string; prompt: string; codex_diff: string; tests: string; reasoning: string; timings: { codex_ms: number; reasoning_ms: number; tests_ms: number } };
const replay: Replay = { agent: "WATCHMAN", prompt: "Audit package dependencies and draft the smallest safe patch.", codex_diff: "package-lock.json\nlodash 4.17.20 → patched release", tests: "Targeted dependency regression replay passed.", reasoning: "The dependency is reachable through a transitive parser path. The compatible patch narrows the blast radius to dependency resolution.", timings: { codex_ms: 1840, reasoning_ms: 926, tests_ms: 4810 } };

function Radar() { const canvas = useRef<HTMLCanvasElement>(null); useEffect(() => { const node = canvas.current; const ctx = node?.getContext("2d"); if (!node || !ctx) return; let frame = 0; let id = 0; const paint = () => { const s = node.clientWidth; const scale = devicePixelRatio; node.width = s * scale; node.height = s * scale; ctx.setTransform(scale, 0, 0, scale, 0, 0); const c = s / 2; ctx.clearRect(0, 0, s, s); ctx.strokeStyle = "rgba(34,211,238,.35)"; [s * .17, s * .33, s * .49].forEach(r => { ctx.beginPath(); ctx.arc(c, c, r, 0, Math.PI * 2); ctx.stroke(); }); ctx.beginPath(); ctx.moveTo(0, c); ctx.lineTo(s, c); ctx.moveTo(c, 0); ctx.lineTo(c, s); ctx.stroke(); const gradient = ctx.createConicGradient(frame * .018, c, c); gradient.addColorStop(0, "rgba(34,211,238,.37)"); gradient.addColorStop(.16, "rgba(34,211,238,0)"); gradient.addColorStop(1, "rgba(34,211,238,0)"); ctx.fillStyle = gradient; ctx.beginPath(); ctx.arc(c, c, s * .49, 0, Math.PI * 2); ctx.fill(); ([[.67, .32, "#fb7185"], [.29, .61, "#facc15"], [.69, .76, "#22d3ee"]] as const).forEach(([x, y, color]) => { ctx.fillStyle = color; ctx.shadowColor = color; ctx.shadowBlur = 12; ctx.beginPath(); ctx.arc(s * x, s * y, 3.5, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; }); frame++; id = requestAnimationFrame(paint); }; paint(); return () => cancelAnimationFrame(id); }, []); return <canvas ref={canvas} className="radar-canvas" aria-label="Animated threat radar" />; }

export default function Home() {
  const [activeReplay, setActiveReplay] = useState<Replay | null>(null);
  const [events, setEvents] = useState<string[][]>(seedEvents.map(event => [...event]));
  useEffect(() => { const source = new EventSource("http://localhost:8000/api/events"); source.addEventListener("umbra", event => { try { const incoming = JSON.parse(event.data); setEvents(current => [[String(incoming.time ?? "NOW"), String(incoming.agent ?? "UMBRA"), String(incoming.message ?? "Event received"), incoming.level === "critical" ? "critical" : "cyan"], ...current].slice(0, 5)); } catch { /* seeded demo remains visible */ } }); return () => source.close(); }, []);
  return <main>
    <div className="aurora one" /><div className="aurora two" />
    <nav><div className="brand"><span>◐</span> UMBRA</div><div className="nav-state"><em /> NIGHT SHIFT ACTIVE</div><button>Launch scan <span>↗</span></button></nav>
    <section className="hero"><div><p className="eyebrow">MISSION CONTROL / 03:17 AM</p><h1>Your repo never<br /><strong>sleeps alone.</strong></h1><p className="lede">Umbra finds vulnerabilities, traces incidents, reviews risk, and drafts the pull requests your team sees in the morning.</p><div className="actions"><button className="primary">View night shift <span>→</span></button><button className="ghost">Ask Umbra <span>⌘ K</span></button></div></div><article className="score glass"><p>UMBRA SCORE <small>↗ 6 this week</small></p><div className="score-row"><strong>82</strong><span>/100<br /><b>RESILIENT</b></span></div><div className="meter"><i /></div><footer><span>Security <b>88</b></span><span>Quality <b>79</b></span><span>Velocity <b>80</b></span></footer></article></section>
    <section className="grid"><article className="terminal glass"><header><div><p className="eyebrow">LIVE AGENT TERMINAL</p><h2>Night shift activity</h2></div><span className="live"><i /> STREAMING</span></header><div className="feed">{events.map(([time, agent, text, tone], index) => <div className="event" key={`${time}-${index}`}><time>{time}</time><b className={tone}>{agent}</b><span>{text}</span><button onClick={() => setActiveReplay({ ...replay, agent })} aria-label="Open reasoning replay">↗</button></div>)}</div><footer><span className="prompt">›</span> Waiting for next mission<span className="cursor">_</span></footer></article><article className="glass radar-card"><header><div><p className="eyebrow">THREAT RADAR</p><h2>Attack surface</h2></div><span className="risk">2 open risks</span></header><div className="radar-wrap"><Radar /><div className="radar-copy"><b>HIGH</b><p>Dependency<br />exposure</p><small>OWASP A06</small></div></div></article></section>
    <section className="agents"><div><p className="eyebrow">THE NIGHT CREW</p><h2>Five specialists. One quiet shift.</h2></div><div className="agent-list">{[["◉", "WATCHMAN", "Hunts CVEs", "#22D3EE"], ["◈", "REVIEWER", "Sees risk", "#A78BFA"], ["⌁", "DETECTIVE", "Traces cause", "#F9A8D4"], ["◒", "JANITOR", "Clears debt", "#5EEAD4"], ["?", "ASK UMBRA", "Answers codebase questions", "#FDE68A"]].map(([mark, name, job, color]) => <article className="glass" key={name}><i style={{ color }}>{mark}</i><b>{name}</b><span>{job}</span></article>)}</div></section>
    {activeReplay && <div className="modal-backdrop" role="presentation" onClick={() => setActiveReplay(null)}><section className="replay glass" role="dialog" aria-modal="true" aria-label="Reasoning Replay" onClick={event => event.stopPropagation()}><button className="close" onClick={() => setActiveReplay(null)}>×</button><p className="eyebrow">REASONING REPLAY / {activeReplay.agent}</p><h2>Every action, inspectable.</h2><div className="replay-step"><span>01</span><div><b>Mission prompt</b><p>{activeReplay.prompt}</p></div></div><div className="replay-step"><span>02</span><div><b>Codex draft</b><pre>{activeReplay.codex_diff}</pre></div><small>{activeReplay.timings.codex_ms}ms</small></div><div className="replay-step"><span>03</span><div><b>Test evidence</b><p>{activeReplay.tests}</p></div><small>{activeReplay.timings.tests_ms}ms</small></div><div className="replay-step"><span>04</span><div><b>GPT-5.6 reasoning</b><p>{activeReplay.reasoning}</p></div><small>{activeReplay.timings.reasoning_ms}ms</small></div><footer>Draft only · Human review required · Never auto-merged</footer></section></div>}
  </main>;
}
